### ISSUE TITLE
Historic England Listing Data

### ISSUE THREAD

**Issue by aelmekeev** [HistoricEngland/arches-bngpoint#9]
Hello @csmith-he, @aj-he,

Sorry for this weird way of using github, but I was wondering if you can help me with the below request I've sent to `heritagelistenquiries` and `DataDownloads` mailboxes a couple of months back.

I've recently started to collect years on the facades of the buildings (https://github.com/aelmekeev/year-on-facade). I wanted to thank the Historic England team since the website has helped me a lot with the current state of this collection.

In addition, I wonder if there is a chance to **get access to the Historic England database via API or extend the Listing data with details from the Official List Entry**. This should help me with the phase 2 of the collection - start looking at the items outside of London.

I can still use the same method I've used in the first phase, i.e. use an Advanced search feature with the date range limited to the year I'm looking for. Unfortunately, running a search like this for 1867 results in 1437 items and even adding "List entry text contains Inscribed" returns 57. The flexibility of API or local dataset would allow me to work with the data much more efficiently.

Looking forward to hearing from you

Best regards,
Alex

**Comment by aj-he** [comment]
Hi @aelmekeev 

At the moment there is no external facing API for the designation system and I'm not aware of plans to extend the downloadable datasets. The team running heritage list enquiries might be able to get something produced for you as a custom dataset.

You could try the heritage gateway but I know that the functionality there is not great. There are plans to replace this but they are at an early stage.

Sorry we couldn't provide any extra help
